server:
  port: 8000

api.url1: https://randomuser.me/api/
api.url2: https://gorest.co.in/public/v2/users
api.url3: https://reqres.in/api/users?page=2
api.url4: https://jsonplaceholder.typicode.com/users