server:
  port: 8000

api.url1: https://randomuser.me/api/
api.url2: https://gorest.co.in/public/v2/users
api.url3: https://reqres.in/api/users?page=2
api.url4: https://jsonplaceholder.typicode.com/users

spring:
  devtools:
    livereload.enabled: true
    restart.enabled: true
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3309/security
    hikari:
      username: cos
      password: 1234
      connectionTimeout: 10000
      maximum-pool-size: 15
      max-lifetime: 600000
      readOnly: false
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true